# Site settings
title: Armstrong CSS
email: adam@rocketmakers.com
description: Armstrong CSS is a lightweight, simple CSS framework that helps you started but won't get in the way
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://armstrongcss.org" # the base hostname & protocol for your site
twitter_username: armstrongcss
github_username:  rocketmakers

# Build settings
# Build settings
markdown: redcarpet
