# Site settings
title: Armstrong
email: armstrong@rocketmakers.com
description: Armstrong is a CSS library
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.armstrongcss.org" # the base hostname & protocol for your site
twitter_username: armstrongcss
github_username:  rocketmakers

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
